logs:
 - name: root
   level: INFO
   format: '%d%T%m%n'
   appenders:
    - type: FileLogAppender
      path: '../tests/test_log.txt'
    - type: StdoutLogAppender

 - name: system
   level: DEBUG
   format: '%d%T%m%n'
   appenders:
    - type: FileLogAppender
      path: '../tests/test_log.txt'
    - type: StdoutLogAppender


system:
 port: 9900
 value: 15
 int_vec: [5,6,7]
 int_list: [8,9,10]
 int_set: [80, 90, 100]
 int_hashset: [77, 88, 99]
 int_map:
  k: 200
  b: 100
 int_unordered_map:
  k1: 300
  b1: 400